// app.js — reads everything from CONFIG (config.js)
// DO NOT edit this file for content changes. Edit config.js instead.

var App = {
  currentSection: 'professional',
  socialFilter: 'all',
  techSearch: '',
  socialSearch: '',

  init: function() {
    this.applyProfile();
    this.setupTheme();
    this.setupNav();
    this.setupParticles();
    this.setupTypewriter();
    this.setupBackToTop();
    this.setupScrollReveal();
    this.setupEasterEgg();
    this.setupPWA();
    this.fetchProfilePic();
    this.renderYouTube();
    this.renderReels();
    this.renderTechBlogs();
    this.renderSocialBlogs();
    this.setupSocialFilters();
  },

  applyProfile: function() {
    var p = CONFIG.profile;
    var s = CONFIG.socials;
    document.querySelectorAll('[data-role]').forEach(function(el) { el.textContent = p.role + ' at ' + p.company; });
    document.querySelectorAll('[data-name]').forEach(function(el) { el.textContent = p.name; });
    document.querySelectorAll('[data-linkedin]').forEach(function(el) { el.href = s.linkedin; });
    document.querySelectorAll('[data-resume-pdf]').forEach(function(el) { el.href = p.resumePDF; });
    var summary = document.getElementById('resumeSummary');
    if (summary) summary.querySelector('p').textContent = p.resumeSummary;
    var aboutLine1 = document.getElementById('aboutLine1');
    if (aboutLine1) aboutLine1.innerHTML = "Hey, I'm <strong>" + p.name + "</strong> — " + p.aboutLine1;
    var aboutLine2 = document.getElementById('aboutLine2');
    if (aboutLine2) aboutLine2.innerHTML = p.aboutLine2;
    // Render dynamic resume sections
    this.renderExperience();
    this.renderSkills();
    this.renderEducation();
    this.renderCerts();
    this.renderHobbies();
  },

  renderExperience: function() {
    var el = document.getElementById('experienceTimeline');
    if (!el) return;
    el.innerHTML = CONFIG.experience.map(function(job) {
      return '<div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content"><div class="timeline-header"><h4>' + job.title + '</h4><span class="timeline-date">' + job.date + '</span></div><p class="timeline-company"><i class="fas fa-building"></i> ' + job.company + ' · ' + job.location + '</p><ul class="timeline-list">' + job.bullets.map(function(b) { return '<li>' + b + '</li>'; }).join('') + '</ul></div></div>';
    }).join('');
  },

  renderSkills: function() {
    var el = document.getElementById('skillsGrid');
    if (!el) return;
    el.innerHTML = CONFIG.skills.map(function(s) {
      return '<div class="skill-group"><h5>' + s.label + '</h5><div class="skill-pills">' + s.items.map(function(i) { return '<span>' + i + '</span>'; }).join('') + '</div></div>';
    }).join('');
  },

  renderEducation: function() {
    var el = document.getElementById('educationTimeline');
    if (!el) return;
    el.innerHTML = CONFIG.education.map(function(e) {
      return '<div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content"><div class="timeline-header"><h4>' + e.title + '</h4><span class="timeline-date">' + e.date + '</span></div><p class="timeline-company"><i class="fas ' + e.icon + '"></i> ' + e.school + '</p></div></div>';
    }).join('');
  },

  renderCerts: function() {
    var el = document.getElementById('certList');
    if (!el) return;
    el.innerHTML = CONFIG.certifications.map(function(c) {
      return '<div class="cert-item"><i class="fas fa-award"></i> ' + c + '</div>';
    }).join('');
  },

  renderHobbies: function() {
    var el = document.getElementById('hobbyPills');
    if (!el) return;
    el.innerHTML = CONFIG.hobbies.map(function(h) {
      return '<span><i class="fas ' + h.icon + '"></i> ' + h.label + '</span>';
    }).join('');
  },

  switchSection: function(section) {
    this.currentSection = section;
    document.getElementById('professionalSection').style.display = section === 'professional' ? '' : 'none';
    document.getElementById('socialSection').style.display = section === 'social' ? '' : 'none';
    document.getElementById('gamesSection').style.display = section === 'games' ? '' : 'none';
    document.querySelectorAll('.switch-btn').forEach(function(b) { b.classList.toggle('active', b.dataset.section === section); });
    document.getElementById('sectionSwitcher').scrollIntoView({ behavior: 'smooth', block: 'start' });
  },

  fetchProfilePic: function() {
    var ig = CONFIG.instagram;
    fetch('https://www.instagram.com/api/v1/users/web_profile_info/?username=' + ig.username, { headers: { 'X-IG-App-ID': ig.appId } })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        if (data.data && data.data.user.profile_pic_url_hd) {
          document.querySelector('.hero-avatar img').src = data.data.user.profile_pic_url_hd;
        }
      }).catch(function() {});
  },

  renderYouTube: function() {
    document.getElementById('ytScroll').innerHTML = CONFIG.ytVideos.map(function(id) {
      return '<div class="reel-embed-card"><iframe src="https://www.youtube.com/embed/' + id + '" loading="lazy" allowfullscreen></iframe><div class="reel-card-footer"><span>YouTube Short</span><a href="https://www.youtube.com/shorts/' + id + '" target="_blank"><i class="fab fa-youtube"></i> Watch</a></div></div>';
    }).join('');
  },

  renderReels: function() {
    document.getElementById('reelsScroll').innerHTML = CONFIG.reels.map(function(r) {
      return '<div class="reel-embed-card"><iframe src="https://www.instagram.com/p/' + r.code + '/embed" loading="lazy" allowtransparency="true" allowfullscreen="true" scrolling="no"></iframe><div class="reel-card-footer"><span>' + r.date + '</span><a href="https://www.instagram.com/p/' + r.code + '/" target="_blank"><i class="fab fa-instagram"></i> Open</a></div></div>';
    }).join('');
  },

  renderTechBlogs: function() {
    var q = this.techSearch.toLowerCase();
    var list = q ? CONFIG.techBlogs.filter(function(b) { return b.title.toLowerCase().includes(q) || b.preview.toLowerCase().includes(q); }) : CONFIG.techBlogs;
    document.getElementById('techBlogGrid').innerHTML = list.length ? list.map(function(b, i) {
      return '<div class="blog-card reveal" style="animation-delay:' + (i*0.06) + 's" onclick="App.openBlog(' + b.id + ',\'tech\')"><div class="blog-icon-cover tech"><i class="fas ' + b.icon + '"></i></div><div class="blog-body"><div style="display:flex;justify-content:space-between;align-items:start;gap:8px;margin-bottom:6px"><h3 style="margin:0">' + b.title + '</h3><span class="blog-cat tech">tech</span></div><p>' + b.preview + '</p><div class="blog-meta"><span><i class="far fa-calendar"></i> ' + b.date + '</span><span class="read-more">Read <i class="fas fa-arrow-right"></i></span></div></div></div>';
    }).join('') : '<p style="text-align:center;color:var(--text2);padding:40px">No blogs found</p>';
    this.refreshReveal();
  },

  renderSocialBlogs: function(filter) {
    filter = filter || this.socialFilter;
    this.socialFilter = filter;
    var q = this.socialSearch.toLowerCase();
    var list = CONFIG.socialBlogs;
    if (filter !== 'all') list = list.filter(function(b) { return b.cat === filter; });
    if (q) list = list.filter(function(b) { return b.title.toLowerCase().includes(q) || b.preview.toLowerCase().includes(q); });
    document.getElementById('socialBlogGrid').innerHTML = list.length ? list.map(function(b, i) {
      return '<div class="blog-card reveal" style="animation-delay:' + (i*0.06) + 's" onclick="App.openBlog(' + b.id + ',\'social\')"><div class="blog-icon-cover ' + b.cat + '"><i class="fas ' + b.icon + '"></i></div><div class="blog-body"><div style="display:flex;justify-content:space-between;align-items:start;gap:8px;margin-bottom:6px"><h3 style="margin:0">' + b.title + '</h3><span class="blog-cat ' + b.cat + '">' + b.cat + '</span></div><p>' + b.preview + '</p><div class="blog-meta"><span><i class="far fa-calendar"></i> ' + b.date + '</span><span class="read-more">Read <i class="fas fa-arrow-right"></i></span></div></div></div>';
    }).join('') : '<p style="text-align:center;color:var(--text2);padding:40px">No blogs found</p>';
    this.refreshReveal();
  },

  searchTechBlogs: function(val) { this.techSearch = val; this.renderTechBlogs(); },
  searchSocialBlogs: function(val) { this.socialSearch = val; this.renderSocialBlogs(); },

  openBlog: function(id, type) {
    var list = type === 'tech' ? CONFIG.techBlogs : CONFIG.socialBlogs;
    var b = list.find(function(x) { return x.id === id; });
    if (!b) return;
    var url = window.location.href.split('#')[0] + '#blog-' + b.id;
    var shareText = b.title + ' — by @coder_sorcerer';
    var cat = b.cat || 'tech';
    document.getElementById('blogModalBody').innerHTML =
      '<h1>' + b.title + '</h1>' +
      '<div class="blog-modal-meta"><span><i class="far fa-calendar"></i> ' + b.date + '</span><span class="blog-cat ' + cat + '" style="display:inline-block">' + cat + '</span></div>' +
      '<div class="blog-modal-body">' + b.content + '</div>' +
      '<div class="blog-share"><span>Share:</span>' +
      '<a class="share-btn twitter" href="https://twitter.com/intent/tweet?text=' + encodeURIComponent(shareText) + '&url=' + encodeURIComponent(url) + '" target="_blank"><i class="fab fa-x-twitter"></i> Twitter</a>' +
      '<a class="share-btn whatsapp" href="https://wa.me/?text=' + encodeURIComponent(shareText + ' ' + url) + '" target="_blank"><i class="fab fa-whatsapp"></i> WhatsApp</a>' +
      '<button class="share-btn copy" onclick="App.copyLink(\'' + url + '\', this)"><i class="fas fa-link"></i> Copy Link</button></div>';
    var modal = document.getElementById('blogModal');
    modal.classList.add('active');
    document.getElementById('closeBlogModal').onclick = function() { modal.classList.remove('active'); };
    modal.onclick = function(e) { if (e.target === modal) modal.classList.remove('active'); };
  },

  copyLink: function(url, btn) {
    navigator.clipboard.writeText(url).then(function() {
      btn.classList.add('copied');
      btn.innerHTML = '<i class="fas fa-check"></i> Copied!';
      setTimeout(function() { btn.classList.remove('copied'); btn.innerHTML = '<i class="fas fa-link"></i> Copy Link'; }, 2000);
    });
  },

  setupSocialFilters: function() {
    var self = this;
    document.querySelectorAll('#socialBlogFilters .filter-btn').forEach(function(btn) {
      btn.onclick = function() {
        document.querySelectorAll('#socialBlogFilters .filter-btn').forEach(function(b) { b.classList.remove('active'); });
        btn.classList.add('active');
        self.renderSocialBlogs(btn.dataset.filter);
      };
    });
  },

  setupTheme: function() {
    var saved = localStorage.getItem('cs_theme') || 'dark';
    document.documentElement.setAttribute('data-theme', saved);
    var btn = document.getElementById('themeToggle');
    btn.innerHTML = '<i class="fas ' + (saved === 'dark' ? 'fa-sun' : 'fa-moon') + ' theme-icon"></i>';
    btn.onclick = function() {
      var icon = btn.querySelector('.theme-icon');
      icon.classList.add('spin-out');
      setTimeout(function() {
        var next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('data-theme', next);
        localStorage.setItem('cs_theme', next);
        icon.className = 'fas ' + (next === 'dark' ? 'fa-sun' : 'fa-moon') + ' theme-icon spin-in';
        setTimeout(function() { icon.classList.remove('spin-in'); }, 500);
      }, 300);
    };
  },

  setupScrollReveal: function() {
    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(e) { if (e.isIntersecting) e.target.classList.add('visible'); });
    }, { threshold: 0.1 });
    document.querySelectorAll('.section, .blog-card, .timeline-item, .skill-group, .about-card, .cert-item, .project-card, .resume-summary, .resume-block').forEach(function(el) {
      el.classList.add('reveal');
      observer.observe(el);
    });
    this._revealObserver = observer;
  },

  refreshReveal: function() {
    var obs = this._revealObserver;
    if (!obs) return;
    setTimeout(function() {
      document.querySelectorAll('.blog-card.reveal:not(.visible)').forEach(function(el) { obs.observe(el); });
    }, 100);
  },

  setupEasterEgg: function() {
    var logo = document.querySelector('.logo');
    var clicks = 0, timer = null;
    logo.addEventListener('click', function(e) {
      e.preventDefault();
      clicks++;
      clearTimeout(timer);
      timer = setTimeout(function() { clicks = 0; }, 1000);
      if (clicks >= 5) { document.getElementById('easterEgg').classList.add('active'); clicks = 0; }
    });
    var konami = [38,38,40,40,37,39,37,39,66,65], pos = 0;
    document.addEventListener('keydown', function(e) {
      if (e.keyCode === konami[pos]) { pos++; if (pos === konami.length) { document.getElementById('easterEgg').classList.add('active'); pos = 0; } } else pos = 0;
    });
  },

  setupPWA: function() {
    if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(function() {});
    var deferredPrompt = null;
    window.addEventListener('beforeinstallprompt', function(e) {
      e.preventDefault(); deferredPrompt = e;
      var btn = document.getElementById('pwaInstall');
      btn.classList.add('show');
      btn.onclick = function() { deferredPrompt.prompt(); deferredPrompt.userChoice.then(function() { btn.classList.remove('show'); deferredPrompt = null; }); };
    });
  },

  setupNav: function() {
    var hamburger = document.getElementById('hamburger');
    var navLinks = document.getElementById('navLinks');
    hamburger.onclick = function() { navLinks.classList.toggle('open'); };
    navLinks.querySelectorAll('a').forEach(function(a) { a.addEventListener('click', function() { navLinks.classList.remove('open'); }); });
    window.addEventListener('scroll', function() { document.getElementById('navbar').classList.toggle('scrolled', window.scrollY > 50); });
  },

  setupParticles: function() {
    var c = document.getElementById('particles');
    for (var i = 0; i < 25; i++) {
      var p = document.createElement('div');
      p.className = 'particle';
      p.style.cssText = 'left:' + Math.random()*100 + '%;top:' + Math.random()*100 + '%;animation-delay:' + Math.random()*6 + 's;animation-duration:' + (4+Math.random()*4) + 's';
      c.appendChild(p);
    }
  },

  setupTypewriter: function() {
    var words = CONFIG.typewriterWords;
    var el = document.getElementById('typewriter');
    var wi = 0, ci = 0, del = false;
    function tick() {
      el.textContent = words[wi].substring(0, ci);
      if (!del) { ci++; if (ci > words[wi].length) { del = true; setTimeout(tick, 1500); return; } }
      else { ci--; if (ci === 0) { del = false; wi = (wi + 1) % words.length; } }
      setTimeout(tick, del ? 50 : 100);
    }
    tick();
  },

  setupBackToTop: function() {
    var btn = document.getElementById('backToTop');
    window.addEventListener('scroll', function() { btn.classList.toggle('visible', window.scrollY > 400); });
    btn.onclick = function() { window.scrollTo({ top: 0, behavior: 'smooth' }); };
  }
};

document.addEventListener('DOMContentLoaded', function() { App.init(); });
